### PR TITLE
CLI Edgecase Fixes

### LINKED ISSUE #219: CLI: Gracefully fail when version of `@misk` package can't be found
Currently ugly fails when old versions (ie. `0.1.1-alpha-0.1`) run `prebuild` on a new version of CLI.

Functionality should output a warning encouraging upgrade and not include the package in the `package.json`.

### LINKED ISSUE #221: Have cd prior concat with command for more consistent shelljs execution

### LINKED ISSUE #225: Change package template so build task defaults to production mode
Right now `rush` uses it to do builds and we're ending up with development builds in the `palette/demo` artifact. 

Create a new `devBuild` task instead.

### PR DESCRIPTION
**Pull request by adrw**
* [CLOSES #221] Enforce that `prebuild` must run before any `npm run-script` command to ensure that build files are generated in the tab
* Have `-e` commands only run after the full directory search is complete
* Add logging formatters
* Add better edge case error handling for `prebuild` sub tasks (specifically around an empty `package.json` file existing in the directory)
* [CLOSES #219] Streamline error handling and graceful failure when finding the package version associated to a `miskTab.json` version
* Reduce async / await use for shell and `fs` related tasks that were executing inconsistently with the `-e` flag
* [CLOSES #225] Revert `build` script to be executed in `production` env so compression in Webpack still happens

### CODE REVIEW

**Comment by wesleyk** [comment]
Can you add a bit more description? What makes this "robust"?

File: packages/@misk/cli/src/utils/generate.ts [hunk 1]
```diff
@@ -10,24 +17,41 @@ import {
...
+    fs.writeFile(path(dir, Files.gitignore), gitignore),
+    fs.writeFile(path(dir, Files.webpack), webpack)
   ]
 
   // Append non-package JSON files with generated by comment
-  await fs.writeFile(Files.tsconfig, generatedByCLI, { flag: "a" })
-  await fs.writeFile(Files.tslint, generatedByCLI, { flag: "a" })
-  console.log(
-    `[GENERATE] Up to date build files generated using Misk Web version ${getVersion(
+  fs.writeFile(path(dir, Files.tsconfig), generatedByCLI, { flag: "a" })
```
Comment (wesleyk) [inline packages/@misk/cli/src/utils/generate.ts]: huh, what's this 'flag: "a"'?

File: packages/@misk/cli/src/utils/index.ts [hunk 2]
```diff
@@ -33,18 +34,33 @@ export enum Files {
...
+export const parseArgs = (...args: any): { args: any[]; dir: string } => ({
+  args,
+  dir: args[0]
+})
+
+export const remove = async (path: string) => {
+  try {
+    fs.remove(path)
+  } catch (e) {
+    console.log(`[ERROR] ${e}`)
```
Comment (wesleyk) [inline packages/@misk/cli/src/utils/index.ts]: again with exception tracking, why is it alright to not blow up here?

File: packages/@misk/cli/src/utils/index.ts [hunk 3]
```diff
@@ -84,15 +103,20 @@ export const handleCommand = async (
...
       .showHelp()
   } else if (args.each) {
+    const tabs: string[] = []
     klaw(".")
       .on("data", (item: any) => {
         if (item.stats.isFile() && item.path.includes("/miskTab.json")) {
-          const dir = item.path.split("/miskTab.json")[0]
-          cd(dir)
-          handlerFn(dir)
+          tabs.push(item.path.split("/miskTab.json")[0])
```
Comment (wesleyk) [inline packages/@misk/cli/src/utils/index.ts]: are these data structures concurrency safe?

Comment (wesleyk) [reply packages/@misk/cli/src/utils/index.ts]: or are we guaranteed serial execution here?

File: packages/@misk/cli/src/utils/migrate.ts [hunk 4]
```diff
@@ -3,46 +3,63 @@
...
+export const migrateBuildFiles = (...args: any) => {
+  const { dir } = parseArgs(...args)
+  logDebug(tag, "", dir)
+  // Verify valid build files or migrate old build files to new miskweb generated build files
+  let pkgMiskTab: IMiskTabJSON = null
+
+  if (fs.existsSync(path(dir, Files.package))) {
+    let pkg = null
+    try {
+      pkg = fs.readJsonSync(path(dir, Files.package))
```
Comment (wesleyk) [inline packages/@misk/cli/src/utils/migrate.ts]: we're still using exception based control flow here?

File: packages/@misk/cli/src/utils/migrate.ts [hunk 5]
```diff
@@ -3,46 +3,63 @@
...
+    } catch (e) {
+      fs.removeSync(path(dir, Files.package))
```
Comment (wesleyk) [inline packages/@misk/cli/src/utils/migrate.ts]: I thought we catch an exception if the file does _not_ exist, why are we trying to remove it if it doesn't exist?

File: packages/@misk/cli/src/utils/index.ts (hunk 3 above)
Comment (wesleyk) [reply packages/@misk/cli/src/utils/index.ts]: synced offline, no need to worry about concurrent execution here!

File: packages/@misk/cli/src/utils/migrate.ts (hunk 4 above)
Comment (wesleyk) [reply packages/@misk/cli/src/utils/migrate.ts]: synced offline. Ideally we'd use a "isValidJson" API, but for now we'll document why we're using exception-based control flow (we're using it because JSON can get partially written out due to flakiness around node FS APIs).

File: packages/@misk/cli/src/utils/generate.ts (hunk 1 above)
Comment (adrw) [reply packages/@misk/cli/src/utils/generate.ts]: `append` mode https://nodejs.org/api/fs.html#fs_file_system_flags

File: packages/@misk/cli/src/utils/index.ts (hunk 2 above)
Comment (adrw) [reply packages/@misk/cli/src/utils/index.ts]: discussed offline: `fs` library with node doesn't seem to be atomic such that we could use a `file exists` API in an if statement before calling `remove`. If the file doesn't exist, `remove` will throw an error even though it already is in the correct state. From what I've seen online, wrapping in try/catch seems to be the regularly used idiom even though it is an anti-pattern.
